name: yndx_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: null
  cupertino_icons: null
  logger: null
  flutter_bloc: null
  bloc: null
  bloc_concurrency: null
  http: null
  isar_flutter_libs: null
  hive: null
  hive_flutter: null
  collection: null
  go_router: null
  flutter_intl: null
  connectivity_plus:

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: null
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
