name: yndx_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: 
  cupertino_icons: 
  logger: 
  flutter_bloc: 
  bloc: 
  bloc_concurrency: 
  http: 
  isar_flutter_libs: 
  hive: 
  hive_flutter: 
  collection: 
  go_router:

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: 
  flutter_test:
    sdk: flutter
  hive_generator: 

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
