name: yndx_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  logger: ^2.3.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  http: ^1.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  go_router: ^14.2.0
  flutter_intl: ^0.0.1
  url_launcher: ^6.3.0
  equatable:

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail:
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
